### PR TITLE
build: use is-ci before husky install & syntax error in Dockerfile

### PR DESCRIPTION
**Pull request by ericreeves**
entrypoint.sh was a simple fix.  It was a syntax error with the EOF token.

DISCLAIMER:  I AM NOT A NODEJS PERSON.

"husky" is specified in packages.json as a devDependency. yet the Dockerfile is running npm ci with "--production".

With this modification, "husky install" will only be run if the NODE_ENV variable is NOT "production".

I have no idea if this is truly the proper way to resolve this issue for all build use-cases, but now it builds and the resulting container functions properly from my minimal testing (account creation via Ferdium, basic operation).

### CODE REVIEW

**Review by nathanaelhoun — APPROVED** [review]
LGTM! Thanks @ericreeves 😊

**Comment by vraravam** [comment]
@all-contributors please add @ericreeves for code

**Comment by vraravam** [comment]
@all-contributors please add @nathanelhoun for review

**Comment by vraravam** [comment]
https://github.com/all-contributors please add @nathanaelhoun for review

**Comment by vraravam** [comment]
@all-contributors please add @nathanaelhoun for review

**Comment by vraravam** [comment]
@all-contributors please add @ericreeves for infrastructure

**Pull request merged**
