### PR TITLE
Add a linux/arm64 architecture variant to the official container

### PR DESCRIPTION
**Pull request by lnhrdt**
Fixes ferdium/ferdium-server#45

### CODE REVIEW

**Comment by lnhrdt** [comment]
I believe this change will work because the base image ([node:16.15.1-alpine](https://hub.docker.com/_/node?tab=tags&page=1&name=16.15.1-alpine)) supports linux/arm64 but I have not actually tested this change myself (it would be difficult without project access).

CC: @Gibby & @SpecialAro because I saw in the git history you've both contributed to this workflow.

**Comment by Gibby** [comment]
Yep it should, I actually had more listed but decided to just do 1 when I did the initial commit and let PR's like this come in as needed.

**Comment by cino** [comment]
@lnhrdt Thanks for taking the time to create this pull-request!

@ferdium/reviewers I would like to add, that if build time is an issue when building for 2 platforms we can consider running a separate job for each platform parallel.

**Comment by lnhrdt** [comment]
Anyone get a chance to review this yet? Anything I can do to help?

**Comment by SpecialAro** [comment]
Hello @lnhrdt I'm sorry I didn't review this previously... I think this got lost in my notifications.

LGTM, will approve and merge 😄 Thank you for you contribution!

**Review by SpecialAro — APPROVED** [review]

**Pull request merged**
