### PR TITLE
Change logo

### PR DESCRIPTION
**Pull request by dqos**

### CODE REVIEW

**Comment by vraravam** [comment]
@dqos - i dont see the gradient in the new image. is that fine?

**Comment by dqos** [comment]
image
There is 👍🏽

**Review by vraravam — APPROVED** [review]
ok - maybe its just GH visual diff not showing correctly. Approving the PR

**Comment by dqos** [comment]
For your reference, here it is in PS:
image

**Comment by vraravam** [comment]
@all-contributors please add @dqos for design

**Pull request merged**
