### PR TITLE
Add a linux/arm64 architecture variant to the official container (v2)

### LINKED ISSUE #45: Publish multi-arch images
I'm trying to migrate from ferdi-server. Ferdi-server published multi-arch images that included `linux/amd64` and `linux/arm64`. The ferdium-server images only contain `linux/amd64` so I'm unable to run the image on my ARM arch hardware.

Any chance you could start publishing multi-arch images that support ARM, like Ferdi did?

### PR DESCRIPTION
**Pull request by lnhrdt**
@SpecialAro I believe this PR fixes the issue you encountered when you merged #46.

Note: I tried to run the workflow in my fork as you suggested but there is some complexity in your workflow tied to this repo configuration that is difficult to navigate in my fork. As a result I have not been able to fully run the workflow to completion. I believe this PR will work but if other issues come up it would be easier to contribute if we could collaborate or if I could gain some level of project access.

CC: @Gibby

Followup to #46 and #49

Fixes #45

### CODE REVIEW

**Comment by SpecialAro** [comment]
Hey 👋

Thank you! I think this should work. I'm pushing it now to the codebase 😁

**Comment by mzayn** [comment]
thanks for ping. later want to try run

**Comment by SpecialAro** [comment]
@all-contributors please add @lnhrdt for infra

**Comment by lnhrdt** [comment]
Thank you for reviewing and merging @SpecialAro! I'll keep an eye out for the next release so I can test the result.

**Comment by SpecialAro** [comment]
@lnhrdt you're welcome! Thank you very much for this contribution.

Once I get my hands on a computer I can bump a version and release to GH. 😁

**Comment by SpecialAro** [comment]
@lnhrdt pinging you so you can try out the new build :D https://hub.docker.com/r/ferdium/ferdium-server/tags

**Comment by lnhrdt** [comment]
@SpecialAro I just tested the new multi-architecture image on arm64 (1.3.11). Works great! Thanks for helping along the way.

**Pull request merged**
